# Generated by Django 3.2.25 on 2026-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mask Name')),
                ('image', models.ImageField(upload_to='masks/', verbose_name='Mask Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image File'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Image Title'),
        ),
    ]
