# Generated by Django 3.2.25 on 2026-06-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20260416_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='mask',
            name='user_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masks', to='hello.userimage', verbose_name='Related User Image'),
        ),
    ]
