# Generated by Django 3.2.25 on 2026-06-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_mask_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mask',
            new_name='UserMask',
        ),
        migrations.CreateModel(
            name='RadiomicsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.JSONField()),
                ('user_mask', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='radiomics_result', to='hello.usermask', verbose_name='Related User Mask')),
            ],
            options={
                'db_table': 'hello_radiomics_result',
            },
        ),
    ]
